### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sibukixxx** [sibukixxx/tride#3]
- [ ] Buttom メニュー / ページ遷移: https://qiita.com/takattata/items/5fa560a95d19623d26fe
- [ ] Routing 学習: https://github.com/tatsu/libraries_in_japan/blob/master/lib/main.dart / https://qiita.com/tatsu/items/38cd85efd93005b95af9
- [ ] APIでデータ取得 / https://qiita.com/yasutaka_ono/items/6d2a0d3b0856598f9788
- [ ] プロジェクト全体を見通す練習 / https://note.mu/shogoyamada/n/n912c7ba1ddf4
- [ ] レイアウトのチート / https://github.com/bizz84/layout-demo-flutter
- [ ] 講座で学ぶその１ / https://qiita.com/aoinakanishi/items/b384e5a88ea4f6dc4b3d
- [ ] その２ / https://qiita.com/aoinakanishi/items/f0e45d525e252c5764b5
- [ ] いろいろなパターンを読む / https://medium.com/flutter-jp/flutter-learning-c5640c5f05b9
- [ ] サーバーサイド認証
- [ ] ローカルDB https://iganin.hatenablog.com/entry/2019/01/09/010804 、 https://github.com/iampawan/Flutter-Sqflite-MVP
- [ ] 本番環境デプロイ、apk / Test Flight 公開 / https://qiita.com/rkowase/items/f1012ef0738791dd6084
